services:
  django:
    env_file:
      - .env
    build:
      context: .
      dockerfile: django.Dockerfile
    container_name: django
    command: >
      sh -c "gunicorn --workers 4 --timeout 30 --bind 0.0.0.0:8000 --access-logfile - ar_tobolsk.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  celery:
    env_file:
      - .env
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: celery
    command: celery -A ar_tobolsk worker -l info -E --concurrency=1
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
      - postgres
    restart: unless-stopped

  flower:
    env_file:
      - .env
    image: mher/flower
    container_name: flower
    command: >
      python -m flower --broker=redis://redis:6379/0
                    --port=5555
                    --persistent=True
                    --db=/flower/flower.db
                    --basic_auth=admin:ar_tobolsk
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/flower
    depends_on:
      - redis
      - celery

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ar_tobolsk
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ar_tobolsk
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  media_volume:
  flower_data: